apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - policy-tenant-scaffold.yaml
  - policy-require-team-label.yaml
  - policy-workload-baseline.yaml
  - policy-gitops-only.yaml
